"""initial schema

Revision ID: 67dbe9434e07
Revises: 
Create Date: 2026-04-18 11:36:33.747365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67dbe9434e07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('extraction_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('best_pipeline', sa.String(length=50), nullable=True),
    sa.Column('best_user_agent', sa.Text(), nullable=True),
    sa.Column('best_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimal_delay_ms', sa.Integer(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=False),
    sa.Column('requires_js', sa.Boolean(), nullable=False),
    sa.Column('has_antibot', sa.Boolean(), nullable=False),
    sa.Column('antibot_type', sa.String(length=100), nullable=True),
    sa.Column('has_api', sa.Boolean(), nullable=False),
    sa.Column('api_endpoint', sa.Text(), nullable=True),
    sa.Column('page_structure_hash', sa.String(length=64), nullable=True),
    sa.Column('last_selectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selector_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id')
    )
    op.create_table('visit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pipeline_name', sa.String(length=50), nullable=False),
    sa.Column('pipeline_sequence', sa.Integer(), nullable=True),
    sa.Column('pipelines_attempted', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('method_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proxy_used', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_size_bytes', sa.Integer(), nullable=True),
    sa.Column('items_extracted', sa.Integer(), nullable=True),
    sa.Column('antibot_detected', sa.String(length=100), nullable=True),
    sa.Column('captcha_encountered', sa.Boolean(), nullable=False),
    sa.Column('captcha_solved', sa.Boolean(), nullable=False),
    sa.Column('healing_applied', sa.Boolean(), nullable=False),
    sa.Column('healing_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visit_logs_success', 'visit_logs', ['success', 'visited_at'], unique=False)
    op.create_index('idx_visit_logs_time', 'visit_logs', ['visited_at'], unique=False)
    op.create_index('idx_visit_logs_url', 'visit_logs', ['url_id', 'visited_at'], unique=False)
    op.create_table('scraped_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('visit_log_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_log_id'], ['visit_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraped_data_url', 'scraped_data', ['url_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scraped_data_url', table_name='scraped_data')
    op.drop_table('scraped_data')
    op.drop_index('idx_visit_logs_url', table_name='visit_logs')
    op.drop_index('idx_visit_logs_time', table_name='visit_logs')
    op.drop_index('idx_visit_logs_success', table_name='visit_logs')
    op.drop_table('visit_logs')
    op.drop_table('url_profiles')
    op.drop_table('schedules')
    op.drop_table('alerts')
    op.drop_table('urls')
    # ### end Alembic commands ###
